### ISSUE TITLE
Project To-Do's

### ISSUE THREAD

**Issue by xavierayala-debug** [xavierayala-debug/Mount-Dora-move-here#1]
- [x] Create 5 vertical tabs
- [ ] Find and input information/pictures about the city in each tab
- [ ] Create onclick() JS function for each tab to expand when clicked on and the rest collapse
- [ ]  CSS transition to allow smooth flow of data
